// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-payment-lab/services/mockpay/internal/server"
)

// Injectors from wire.go:

// wireApp 组装依赖注入图:main → server(HealthService/http/grpc)→ kratos.App。
func wireApp(conf *server.Server, logger log.Logger) (*kratos.App, func(), error) {
	healthService := server.NewHealthService()
	httpServer := server.NewHTTPServer(conf, healthService, logger)
	grpcServer := server.NewGRPCServer(conf, healthService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
