// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: commerce/v1/errors/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_SUCCESS ErrorCode = 0
	// 通用错误 1000-1999
	ErrorCode_INTERNAL_ERROR    ErrorCode = 1000
	ErrorCode_INVALID_ARGUMENT  ErrorCode = 1001
	ErrorCode_NOT_FOUND         ErrorCode = 1002
	ErrorCode_ALREADY_EXISTS    ErrorCode = 1003
	ErrorCode_PERMISSION_DENIED ErrorCode = 1004
	ErrorCode_UNAUTHENTICATED   ErrorCode = 1005
	// 订单相关 2000-2999
	ErrorCode_ORDER_INVALID_STATUS_TRANSITION ErrorCode = 2000
	ErrorCode_ORDER_NOT_FOUND                 ErrorCode = 2001
	ErrorCode_ORDER_CANNOT_BE_MODIFIED        ErrorCode = 2002
	// 支付相关 3000-3999
	ErrorCode_PAYMENT_INVALID_STATUS_TRANSITION ErrorCode = 3000
	ErrorCode_PAYMENT_FAILED                    ErrorCode = 3001
	ErrorCode_PAYMENT_ALREADY_PROCESSED         ErrorCode = 3002
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "SUCCESS",
		1000: "INTERNAL_ERROR",
		1001: "INVALID_ARGUMENT",
		1002: "NOT_FOUND",
		1003: "ALREADY_EXISTS",
		1004: "PERMISSION_DENIED",
		1005: "UNAUTHENTICATED",
		2000: "ORDER_INVALID_STATUS_TRANSITION",
		2001: "ORDER_NOT_FOUND",
		2002: "ORDER_CANNOT_BE_MODIFIED",
		3000: "PAYMENT_INVALID_STATUS_TRANSITION",
		3001: "PAYMENT_FAILED",
		3002: "PAYMENT_ALREADY_PROCESSED",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":                           0,
		"INTERNAL_ERROR":                    1000,
		"INVALID_ARGUMENT":                  1001,
		"NOT_FOUND":                         1002,
		"ALREADY_EXISTS":                    1003,
		"PERMISSION_DENIED":                 1004,
		"UNAUTHENTICATED":                   1005,
		"ORDER_INVALID_STATUS_TRANSITION":   2000,
		"ORDER_NOT_FOUND":                   2001,
		"ORDER_CANNOT_BE_MODIFIED":          2002,
		"PAYMENT_INVALID_STATUS_TRANSITION": 3000,
		"PAYMENT_FAILED":                    3001,
		"PAYMENT_ALREADY_PROCESSED":         3002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_commerce_v1_errors_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_commerce_v1_errors_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_commerce_v1_errors_errors_proto_rawDescGZIP(), []int{0}
}

type ErrDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=errors.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrDetail) Reset() {
	*x = ErrDetail{}
	mi := &file_commerce_v1_errors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrDetail) ProtoMessage() {}

func (x *ErrDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commerce_v1_errors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrDetail.ProtoReflect.Descriptor instead.
func (*ErrDetail) Descriptor() ([]byte, []int) {
	return file_commerce_v1_errors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_SUCCESS
}

func (x *ErrDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_commerce_v1_errors_errors_proto protoreflect.FileDescriptor

const file_commerce_v1_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x1fcommerce/v1/errors/errors.proto\x12\x06errors\"\xc6\x01\n" +
	"\tErrDetail\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.errors.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.errors.ErrDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xcf\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xe8\a\x12\x15\n" +
	"\x10INVALID_ARGUMENT\x10\xe9\a\x12\x0e\n" +
	"\tNOT_FOUND\x10\xea\a\x12\x13\n" +
	"\x0eALREADY_EXISTS\x10\xeb\a\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\xec\a\x12\x14\n" +
	"\x0fUNAUTHENTICATED\x10\xed\a\x12$\n" +
	"\x1fORDER_INVALID_STATUS_TRANSITION\x10\xd0\x0f\x12\x14\n" +
	"\x0fORDER_NOT_FOUND\x10\xd1\x0f\x12\x1d\n" +
	"\x18ORDER_CANNOT_BE_MODIFIED\x10\xd2\x0f\x12&\n" +
	"!PAYMENT_INVALID_STATUS_TRANSITION\x10\xb8\x17\x12\x13\n" +
	"\x0ePAYMENT_FAILED\x10\xb9\x17\x12\x1e\n" +
	"\x19PAYMENT_ALREADY_PROCESSED\x10\xba\x17B\x19Z\x17/api/commerce/v1/errorsb\x06proto3"

var (
	file_commerce_v1_errors_errors_proto_rawDescOnce sync.Once
	file_commerce_v1_errors_errors_proto_rawDescData []byte
)

func file_commerce_v1_errors_errors_proto_rawDescGZIP() []byte {
	file_commerce_v1_errors_errors_proto_rawDescOnce.Do(func() {
		file_commerce_v1_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commerce_v1_errors_errors_proto_rawDesc), len(file_commerce_v1_errors_errors_proto_rawDesc)))
	})
	return file_commerce_v1_errors_errors_proto_rawDescData
}

var file_commerce_v1_errors_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commerce_v1_errors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_commerce_v1_errors_errors_proto_goTypes = []any{
	(ErrorCode)(0),    // 0: errors.ErrorCode
	(*ErrDetail)(nil), // 1: errors.ErrDetail
	nil,               // 2: errors.ErrDetail.MetadataEntry
}
var file_commerce_v1_errors_errors_proto_depIdxs = []int32{
	0, // 0: errors.ErrDetail.code:type_name -> errors.ErrorCode
	2, // 1: errors.ErrDetail.metadata:type_name -> errors.ErrDetail.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_commerce_v1_errors_errors_proto_init() }
func file_commerce_v1_errors_errors_proto_init() {
	if File_commerce_v1_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commerce_v1_errors_errors_proto_rawDesc), len(file_commerce_v1_errors_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commerce_v1_errors_errors_proto_goTypes,
		DependencyIndexes: file_commerce_v1_errors_errors_proto_depIdxs,
		EnumInfos:         file_commerce_v1_errors_errors_proto_enumTypes,
		MessageInfos:      file_commerce_v1_errors_errors_proto_msgTypes,
	}.Build()
	File_commerce_v1_errors_errors_proto = out.File
	file_commerce_v1_errors_errors_proto_goTypes = nil
	file_commerce_v1_errors_errors_proto_depIdxs = nil
}
