// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Balance   int64
	CreatedAt pgtype.Timestamptz
}

type Order struct {
	ID          int64
	OrderNo     string
	UserID      int64
	AmountCents int64
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PaymentAttempt struct {
	ID                 int64
	OrderNo            string
	AmountCents        int64
	Channel            string
	IdempotencyKey     string
	RequestFingerprint string
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
