// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package query

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (order_no, user_id, amount_cents, status)
VALUES ($1, $2, $3, $4)
RETURNING id, order_no, user_id, amount_cents, status, version, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNo     string
	UserID      int64
	AmountCents int64
	Status      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNo,
		arg.UserID,
		arg.AmountCents,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNo = `-- name: GetOrderByOrderNo :one
SELECT id, order_no, user_id, amount_cents, status, version, created_at, updated_at
FROM orders
WHERE order_no = $1
LIMIT 1
`

func (q *Queries) GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNo, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionOrder = `-- name: TransitionOrder :execrows
UPDATE orders
SET status = $1, version = version + 1, updated_at = now()
WHERE order_no = $2 AND status = ANY($3::varchar[])
`

type TransitionOrderParams struct {
	ToStatus   string
	OrderNo    string
	FromStatus []string
}

func (q *Queries) TransitionOrder(ctx context.Context, arg TransitionOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionOrder, arg.ToStatus, arg.OrderNo, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
