// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attempts.sql

package query

import (
	"context"
)

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    order_no,
    amount_cents,
    channel,
    idempotency_key,
    request_fingerprint,
    status
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           'PENDING'
       )
    RETURNING id, order_no, amount_cents, channel, idempotency_key, request_fingerprint, status, created_at, updated_at
`

type CreatePaymentAttemptParams struct {
	OrderNo            string
	AmountCents        int64
	Channel            string
	IdempotencyKey     string
	RequestFingerprint string
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.OrderNo,
		arg.AmountCents,
		arg.Channel,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Channel,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptById = `-- name: GetPaymentAttemptById :one
SELECT id, order_no, amount_cents, channel, idempotency_key, request_fingerprint, status, created_at, updated_at
FROM payment_attempts
WHERE id = $1
`

func (q *Queries) GetPaymentAttemptById(ctx context.Context, id int64) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptById, id)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Channel,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKey = `-- name: GetPaymentAttemptByIdempotencyKey :one
SELECT id, order_no, amount_cents, channel, idempotency_key, request_fingerprint, status, created_at, updated_at
FROM payment_attempts
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentAttemptByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKey, idempotencyKey)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Channel,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
